// Code generated by airlock; DO NOT EDIT.
package main

import (
	"fmt"
	"sammyjroberts/airlock/airlock"
)

type MathCaller struct {
	airlock.ProxyBase
}

func NewMathCaller(sockPath string) *MathCaller {
	return &MathCaller{
		ProxyBase: airlock.ProxyBase{SockPath: sockPath},
	}
}

func (c *MathCaller) Add(arg0 int, arg1 int) (int, error) {
	result, err := c.Call("Add", arg0, arg1)
	if err != nil {
		return 0, err
	}
	typedResult, ok := airlock.ToInt(result)
	if !ok {
		return 0, fmt.Errorf("unexpected result type: %T", result)
	}
	return typedResult, nil

}

func (c *MathCaller) Subtract(arg0 int, arg1 int) (int, error) {
	result, err := c.Call("Subtract", arg0, arg1)
	if err != nil {
		return 0, err
	}

	typedResult, ok := result.(int)
	if !ok {
		return 0, fmt.Errorf("unexpected result type: %T", result)
	}
	return typedResult, nil

}

func (c *MathCaller) Multiply(arg0 int, arg1 int) (int, error) {
	result, err := c.Call("Multiply", arg0, arg1)
	if err != nil {
		return 0, err
	}

	typedResult, ok := result.(int)
	if !ok {
		return 0, fmt.Errorf("unexpected result type: %T", result)
	}
	return typedResult, nil

}

func (c *MathCaller) Divide(arg0 int, arg1 int) (int, error) {
	result, err := c.Call("Divide", arg0, arg1)
	if err != nil {
		return 0, err
	}

	typedResult, ok := result.(int)
	if !ok {
		return 0, fmt.Errorf("unexpected result type: %T", result)
	}
	return typedResult, nil

}
